# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Muhammad Hammad Tufail Bhutta
title: Working Student (Driver Assistance Systems and Autonomous Driving) at Bosch
email: hammadbhutta786@gmail.com
website: https://github.com/HammadTufail/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  HammadTufail
linkedin_username: hammad-tufail-55bb0914a

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Grounded and solution-oriented Computer Scientist with a wide variety of research and professional experiences. Adept at motivating self and others. Passionate about deep learning and software engineering. A poised individual with strong technical and interpersonal skills.
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: GhostNet-Anomalous Event Detection and Extraction using 3D CNN
        link: https://github.com/HammadTufail/GhostNet
        # link_text: Project Website
        additional_links:
          - title:  HammadTufail/GhostNet
            icon: fab fa-github
            url: https://github.com/HammadTufail/GhostNet

        quote: >
          This is an intelligent AI system that can extract different anamoulous events(Accidents, robbery, Shoplifting etc) from CCTV streams and static videos
        description: >-

          - This R&D project is aimed at resolving the longstanding security issues that metropolitan cities have by automating the detection of different anomalous events(Shooting, Road Accidents, Explosions, etc). It is categorized under the Action Recognition problem.
          Knowledge distillation is used to teach the RGB model how to mimic optical flow calculation. This makes this model a very optimal solution as it requires very few calculations as compared to RGB + Optical Flow, while it retains accuracy.
          - We modified the UCF Crime dataset, converting it into a 14-class problem rather than the two-class problem. This volume of this dataset is not sufficient to train an accurate model, so it was first trained on the Kinetic-400 dataset to enrich it with the global features. Then we used our Crime dataset to feed the last layers for the local features.
          - As for the architecture of the model itself, we have used ResNeXt (a 3D variant of ResNet) as it was computationally less intensive.
          - For extracting events, we used a sliding time window that seeks anomalous events in that current window and then chain the event scores with the previous and upcoming scores, if applicable.
          - Flask was used to prototype a website and deploy the model for User interaction. The model was coded in PyTorch and was supported with NumPy, Scikit-learn, and Pandas. The model was tested both on CPU(i7 8700k) and GPU(GTX 1080ti). GPU version fetched a total of 52fps and CPU version, after model pruning, fetched 14 fps.
          - I used GCP compute instance to serve the model to client and used load balancer to add computer power in case we need to serve the same model to multiple clients.




  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
